# Generated by Django 6.0.6 on 2026-06-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketingSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Small label at top, e.g. HIRE A CAR", max_length=40
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        help_text="Two-line headline. Use \\n for line break.",
                        max_length=80,
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        choices=[
                            ("car", "Car (Hire a Car)"),
                            ("seat", "Seat (Book a Seat)"),
                            ("phone", "Phone (Easy Booking)"),
                            ("driver", "Driver (Know Your Driver)"),
                            ("city", "City (About TWMB)"),
                            ("shield", "Shield (Safe Rides)"),
                            ("savings", "Piggy Bank (Save Money)"),
                            ("star", "Star (Top Rated)"),
                            ("route", "Route (Plan Your Trip)"),
                            ("group", "Group (Shared Rides)"),
                        ],
                        default="car",
                        max_length=20,
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        default="#FFC300",
                        help_text="Hex colour, e.g. #FFC300",
                        max_length=7,
                    ),
                ),
                ("text_color", models.CharField(default="#1A1A1A", max_length=7)),
                ("accent_color", models.CharField(default="#E6A800", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower = shown first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "marketing_slides",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
