# Generated by Django 6.0.6 on 2026-06-20 19:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_name", models.CharField(max_length=255)),
                ("origin_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("origin_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("destination_name", models.CharField(max_length=255)),
                (
                    "destination_lat",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "destination_lng",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("departure_time", models.TimeField()),
                ("monday", models.BooleanField(default=False)),
                ("tuesday", models.BooleanField(default=False)),
                ("wednesday", models.BooleanField(default=False)),
                ("thursday", models.BooleanField(default=False)),
                ("friday", models.BooleanField(default=False)),
                ("saturday", models.BooleanField(default=False)),
                ("sunday", models.BooleanField(default=False)),
                ("total_seats", models.PositiveSmallIntegerField()),
                ("minimum_riders", models.PositiveSmallIntegerField(default=1)),
                (
                    "route_fare",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "private_fare",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_trips",
                        to="accounts.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "recurring_trips",
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_name", models.CharField(max_length=255)),
                ("origin_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("origin_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("destination_name", models.CharField(max_length=255)),
                (
                    "destination_lat",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "destination_lng",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("departure_time", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("shared", "Shared"), ("private", "Private")],
                        default="shared",
                        max_length=10,
                    ),
                ),
                ("total_seats", models.PositiveSmallIntegerField()),
                ("available_seats", models.PositiveSmallIntegerField()),
                ("minimum_riders", models.PositiveSmallIntegerField(default=1)),
                ("route_fare", models.DecimalField(decimal_places=2, max_digits=8)),
                ("private_fare", models.DecimalField(decimal_places=2, max_digits=8)),
                ("booking_window_open", models.BooleanField(default=True)),
                (
                    "booking_window_closes_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips_as_driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recurring_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances",
                        to="trips.recurringtrip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="accounts.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "trips",
                "ordering": ["departure_time"],
            },
        ),
    ]
