# Generated by Django 6.0.6 on 2026-06-22 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="mode",
            field=models.CharField(
                choices=[
                    ("shared", "Shared"),
                    ("private", "Private"),
                    ("dynamic", "Dynamic"),
                ],
                default="shared",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="RideRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_name", models.CharField(max_length=255)),
                ("origin_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("origin_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("destination_name", models.CharField(max_length=255)),
                (
                    "destination_lat",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "destination_lng",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("shared", "Shared"),
                            ("private", "Private"),
                            ("dynamic", "Dynamic"),
                        ],
                        default="dynamic",
                        max_length=10,
                    ),
                ),
                ("fare_estimate", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="joined_requests",
                        to="trips.trip",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ride_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
