# Generated by Django 6.0.6 on 2026-06-24 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0002_alter_trip_mode_riderequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderequest",
            name="requested_trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="join_requests",
                to="trips.trip",
            ),
        ),
    ]
