# Generated by Django 6.0.6 on 2026-06-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0003_riderequest_add_requested_trip"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringtrip",
            name="mode",
            field=models.CharField(
                choices=[
                    ("shared", "Shared"),
                    ("private", "Private"),
                    ("dynamic", "Dynamic"),
                ],
                default="shared",
                max_length=10,
            ),
        ),
    ]
