# Generated by Django 6.0.6 on 2026-06-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("local", "Local Township (0-5km)"),
                            ("city", "City-wide (5-15km)"),
                            ("intercity", "Inter-city (15-50km)"),
                            ("longhaul", "Long Haul (50km+)"),
                        ],
                        max_length=15,
                    ),
                ),
                ("rate_per_km", models.DecimalField(decimal_places=2, max_digits=6)),
                ("is_active", models.BooleanField(default=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pricing_zones",
            },
        ),
    ]
