# Generated by Django 6.0.6 on 2026-06-22 11:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="budget_dismissed_month",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="budget_dismissed_week",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="fuel_price_per_litre",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("35.00"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="vehicle_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="estimated_service_cost_zmw",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("500.00"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="fuel_consumption_l_per_100km",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("10.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="fuel_type",
            field=models.CharField(
                choices=[("petrol", "Petrol"), ("diesel", "Diesel")],
                default="petrol",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="last_service_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="last_service_odometer_km",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="service_interval_km",
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="service_interval_months",
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
