# Generated by Django 6.0.6 on 2026-06-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_strike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("driver", "Driver"), ("rider", "Rider")],
                default="rider",
                max_length=10,
            ),
        ),
    ]
