# Generated by Django 6.0.6 on 2026-06-22 11:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("fuel", "Fuel"),
                            ("parts", "Parts"),
                            ("repair", "Repair"),
                            ("other", "Other"),
                        ],
                        default="fuel",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("cost_zmw", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date", models.DateField(default=datetime.date.today)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "operational_logs",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
