from django.db import models
from django.conf import settings
from django.utils import timezone
from decimal import Decimal
import datetime


class DriverWallet(models.Model):
    """Float balance for the driver (Yango-style cash ride model).
    Driver collects cash from riders. Platform deducts commission from float.
    If float is too low, driver goes offline until they top up.
    """
    driver = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='wallet'
    )
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0'))
    minimum_float = models.DecimalField(max_digits=8, decimal_places=2, default=Decimal('1'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'driver_wallets'

    def __str__(self):
        return f'{self.driver.full_name} — K{self.balance}'

    @property
    def can_accept_rides(self):
        return self.balance >= self.minimum_float

    def deduct(self, amount, description='Commission deduction'):
        self.balance -= Decimal(str(amount))
        self.save(update_fields=['balance', 'updated_at'])
        WalletTransaction.objects.create(
            wallet=self,
            transaction_type=WalletTransaction.TYPE_DEBIT,
            amount=amount,
            description=description,
        )

    def top_up(self, amount, reference='', description='Top up'):
        self.balance += Decimal(str(amount))
        self.save(update_fields=['balance', 'updated_at'])
        WalletTransaction.objects.create(
            wallet=self,
            transaction_type=WalletTransaction.TYPE_CREDIT,
            amount=amount,
            reference=reference,
            description=description,
        )


class WalletTransaction(models.Model):
    TYPE_CREDIT = 'credit'
    TYPE_DEBIT = 'debit'
    TYPE_CHOICES = [
        (TYPE_CREDIT, 'Credit'),
        (TYPE_DEBIT, 'Debit'),
    ]

    wallet = models.ForeignKey(DriverWallet, on_delete=models.CASCADE, related_name='transactions')
    transaction_type = models.CharField(max_length=6, choices=TYPE_CHOICES)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.CharField(max_length=255)
    reference = models.CharField(max_length=100, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'wallet_transactions'
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.transaction_type} K{self.amount} — {self.description}'


class Commission(models.Model):
    """Record of commission deducted per completed trip."""
    STATUS_PENDING = 'pending'
    STATUS_DEDUCTED = 'deducted'
    STATUS_CHOICES = [
        (STATUS_PENDING, 'Pending'),
        (STATUS_DEDUCTED, 'Deducted'),
    ]

    driver = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='commissions'
    )
    trip = models.ForeignKey(
        'trips.Trip', on_delete=models.PROTECT, related_name='commissions'
    )
    trip_revenue = models.DecimalField(max_digits=8, decimal_places=2)
    rate = models.DecimalField(max_digits=4, decimal_places=3)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    status = models.CharField(max_length=8, choices=STATUS_CHOICES, default=STATUS_PENDING)
    deducted_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'commissions'
        ordering = ['-created_at']

    def __str__(self):
        return f'Commission {self.driver.full_name} — K{self.amount} [{self.status}]'

    def deduct(self):
        if self.status == self.STATUS_DEDUCTED:
            return
        wallet = self.driver.wallet
        wallet.deduct(self.amount, description=f'Commission for trip #{self.trip_id}')
        self.status = self.STATUS_DEDUCTED
        self.deducted_at = timezone.now()
        self.save(update_fields=['status', 'deducted_at'])


class TopUpCode(models.Model):
    """One-time voucher code generated by admin. Driver redeems it to credit their float."""
    code = models.CharField(max_length=20, unique=True, db_index=True)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    is_used = models.BooleanField(default=False)
    used_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='redeemed_codes'
    )
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='generated_codes'
    )
    expires_at = models.DateTimeField()
    used_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'topup_codes'
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.code} — K{self.amount} {"(used)" if self.is_used else "(available)"}'


class OperationalLog(models.Model):
    """Driver-entered record of fuel fills, parts, and repairs."""
    TYPE_FUEL = 'fuel'
    TYPE_PARTS = 'parts'
    TYPE_REPAIR = 'repair'
    TYPE_OTHER = 'other'
    TYPE_CHOICES = [
        (TYPE_FUEL, 'Fuel'),
        (TYPE_PARTS, 'Parts'),
        (TYPE_REPAIR, 'Repair'),
        (TYPE_OTHER, 'Other'),
    ]

    driver = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='operational_logs'
    )
    log_type = models.CharField(max_length=10, choices=TYPE_CHOICES, default=TYPE_FUEL)
    description = models.CharField(max_length=200)
    cost_zmw = models.DecimalField(max_digits=8, decimal_places=2)
    date = models.DateField(default=datetime.date.today)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'operational_logs'
        ordering = ['-date', '-created_at']

    def __str__(self):
        return f'{self.driver.full_name} — {self.log_type} K{self.cost_zmw} ({self.date})'
