# Generated by Django 6.0.6 on 2026-06-20 19:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seats_booked", models.PositiveSmallIntegerField(default=1)),
                ("pickup_name", models.CharField(max_length=255)),
                ("pickup_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("pickup_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("dropoff_name", models.CharField(max_length=255)),
                ("dropoff_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("dropoff_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "detour_km",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "detour_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "fare_at_booking",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "fare_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Cash")], default="cash", max_length=10
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending", "confirmed"])),
                        fields=("trip", "rider"),
                        name="unique_active_booking_per_trip_rider",
                    )
                ],
            },
        ),
    ]
