# Generated by Django 6.0.6 on 2026-06-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_ratings_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="picked_up_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
